# Generated by Django 4.1.5 on 2023-01-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicion_medidor_alter_medidor_llaveidentificadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidor',
            name='consumoTotal',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
