# Generated by Django 4.1.5 on 2023-01-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medidor_consumototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='consumoTotal',
            field=models.FloatField(null=True),
        ),
    ]
