# Generated by Django 4.1.5 on 2023-01-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_medidor_consumototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='unidad',
            field=models.CharField(default='KW', max_length=20),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='llaveIdentificadora',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
