# Generated by Django 4.1.5 on 2023-01-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_medicion_unidad_alter_medidor_llaveidentificadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='unidad',
            field=models.CharField(default='kwh', max_length=20),
        ),
    ]
